# Generated by Django 5.1.3 on 2025-01-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_subjects_chatarchive_chat_survey_delete_userprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='answer_10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='answer_8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='answer_9',
            field=models.CharField(default='', max_length=100),
        ),
    ]
